additionalArguments:
  - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--entryPoints.websecure.address=:443"
  - "--entryPoints.websecure.http.encodequerysemicolons=true"
  
ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [web, websecure]
    matchRule: Host(`traefik.k8s.local`)
