ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: [websecure]
    matchRule: Host(`traefik.k8s.local`)
