# Inspired by https://github.com/kube-vip/kube-vip/blob/v0.8.0/pkg/kubevip/config_generator.go#L103
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-vip
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "True"
    - name: port
      value: "6443"
    - name: vip_nodename
      value: kube-dev-node-1
    - name: vip_interface
      value: "ens192"
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: "first"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "False"
    - name: cp_detect
      value: "False"
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: "plndr-svcs-lock"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: "plndr-cp-lock"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: "172.20.0.80"
    - name: lb_fwdmethod
      value: "local"
    image: ghcr.io/kube-vip/kube-vip:v0.8.9
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/super-admin.conf
    name: kubeconfig
status: {}